export const GET_STAFF_MEMBERS = 'GET_STAFF_MEMBERS';

export const SET_STAFF_MEMBERS_PAGE = 'SET_STAFF_MEMBERS_PAGE';

/*
* Staff member Profile
*/

export const STAFF_MEMBER_PROFILE_REQUEST = 'STAFF_MEMBER_PROFILE_REQUEST';
export const STAFF_MEMBER_PROFILE_SUCCESS = 'STAFF_MEMBER_PROFILE_SUCCESS';
export const STAFF_MEMBER_PROFILE_FAILURE = 'STAFF_MEMBER_PROFILE_FAILURE';
