export const initialStaffMembers = [
  {
    id: '1',
    image: 'http://boss-styles.herokuapp.com/images/avatars/download.jpeg',
    name: 'John Doe',
    modified: '18:00 Wed 11/16/2016',
    status: true,
    type: 'Manager',
    masterVenue: 'Black',
    workVenues: 'Mint Green, McCooley\'s',
    accessories: [
      {
        id: '1',
        title: 'Accessory name',
        name: 'Venue name',
        icon: 'accessory',
        quantity: 0,
        color: '#4c4c4c',
      },
      {
        id: '2',
        title: '3 pocket Aprons',
        name: 'Venue name',
        icon: 'apron',
        quantity: 0,
        color: '#cd84f1',
      },
      {
        id: '3',
        title: 'Bar Blade',
        name: 'Venue name',
        icon: 'bar-blade',
        quantity: 2,
        color: '#2ecc71',
      },
      {
        id: '4',
        title: 'Chef Hat',
        name: 'Venue name',
        icon: 'apron',
        quantity: 0,
        color: '#fea47f',
      },
      {
        id: '5',
        title: 'Chef Whites (Coats)',
        name: 'Venue name',
        icon: 'apron',
        quantity: 0,
        color: '#6a89cc',
      },
    ],
    scannable: true,
    retakePicture: false,
  },
  {
    id: '2',
    image: 'http://boss-styles.herokuapp.com/images/avatars/mr.jpg',
    name: 'John Doe',
    modified: '11:00 Fri 11/18/2016',
    status: false,
    type: 'Manager',
    masterVenue: 'Brooklyn Mixer',
    workVenues: 'Black, McCooley\'s',
    accessories: [
      {
        id: '1',
        title: 'Accessory name',
        name: 'Venue name',
        icon: 'accessory',
        quantity: 2,
        color: '#4c4c4c',
      },
      {
        id: '2',
        title: 'Discount card',
        name: 'Venue name',
        icon: 'discount-card',
        quantity: 3,
        color: '#cf6a87',
      },
      {
        id: '3',
        title: 'Tooltip',
        name: 'Venue name',
        icon: 'fob',
        quantity: 0,
        color: '#f97f51',
      },
      {
        id: '4',
        title: 'Hoodie',
        name: 'Venue name',
        icon: 'hoodie',
        quantity: 0,
        color: '#8c7ae6',
      },
    ],
    scannable: false,
    retakePicture: true,
  },
];

export default initialStaffMembers;
